### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by friederbluemle**
This updates all Android dependencies and the Gradle wrapper to the latest version.

It also updates `pmd-java` to the (now) latest version `5.5.4`, superseding #19

<sub><sup>Please NO GitHub rebase/squash merges. If you'd like me to combine some or all of the commits, please let me know, and I will update my branch. Thank you.</sup></sub>

### CODE REVIEW

**Comment by stoyicker** [comment]
@friederbluemle self-plug with some updates and things more-up-to-date: https://github.com/stoyicker/android-check-2

**Comment by smalichenko** [comment]
Dependencies updated in 1.2.4 release.

**Comment by friederbluemle** [comment]
@smalichenko Hmm okay thanks. But what stopped you from merging this PR first, before making the additional changes, which duplicated at least 50% of the work?
Anyway, I opened another PR that updates Gradle wrapper to the latest: #31

**Comment by smalichenko** [comment]
@friederbluemle Sorry, but that's because i've needed only 50% of changes (only dependencies update), but not more.

**Pull request closed without merging**
