### PR TITLE
Update PMD plugin to resolve issue

### PR DESCRIPTION
**Pull request by ghost**
Hi everyone. We discovered some bugs in the previous version of the PMD tool, and we updated the version in build.gradle. The issue was fixed by PMD maintainers in the new version.

### CODE REVIEW

**Comment by stkent** [comment]
I ran into this exception using the plugin w/ defaults today:

> java.lang.IllegalArgumentException: Unable to exclude rules [UncommentedEmptyMethod]; perhaps the rule name is mispelled?

which I believe is related to [this issue](https://sourceforge.net/p/pmd/bugs/1394/) and appears to have been fixed in PMD v5.4.0. Is there anything blocking this PR from being merged?

**Comment by Dushistov** [comment]
Any news about process of merging this, and make new release?

**Comment by stkent** [comment]
Project looks abandoned :/

I help maintain an alternative here: https://github.com/btkelly/gnag. It can be used fully-locally, and also includes optional GitHub-related features (e.g. auto-commenting on pull requests). We're currently using PMD 5.4.2, which is new enough to resolve the issue described above. (Nothing is stopping us from going even newer than that except time :))

**Comment by smalichenko** [comment]
Fixed in 1.2.4 release.

**Pull request closed without merging**
